name: Deploy Node.js and React.js site on 85server
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Detect package manager 
          id: detect-package-manager
          run: |
           cd node
           npm install -f
           npm install -g pm2
           pm2 start app.js
           cd ../reactdemo
           npm install
           npm run build
           
        - name: Setup Node using node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version:  ${{ matrix.node-version }}
            cache: ${{ steps.detect-package-manager.outputs.manager }}
         
        - name: Deploy file to server
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            password: ${{ secrets.FTP_PASSWORD }}
            ssh_private_key: ${{ secrets.SSH_PUBLIC_KEY }}
            remote_path: '/var/www/html/node_react_pipeline'
            sftp_only: true
